### ISSUE TITLE
Whether ARC IoTDK can connect to webcam and apply image processing? 

### ISSUE THREAD

**Issue by CWLiang** [foss-for-synopsys-dwc-arc-processors/embarc_osp#110]
# Question
   I wonder that if ARC IoTDK can connect webcam and apply image processing?
   Is there any sample project or code?

**Comment by CWLiang** [comment]
I wonder that if ARC IoTDK can connect webcam and apply image processing?
Is there any sample project or code?

**Comment by vonhust** [comment]
you cannot use ARC IoTDK to connect Webcam because no usb driver support and limitted resource and performance of ARC IoTDK
