### ISSUE TITLE
How to transform the pre-trained model on caffe or tensorflow to c file for iotdk inference application?

### ISSUE THREAD

**Issue by CWLiang** [foss-for-synopsys-dwc-arc-processors/embarc_osp#113]
# Issue Summary
I want to use ARC iotdk to do some machine learning inference application.
So I reference the example that provided in embarc_osp/example/baremetal/embarc_mli/cifar10_caffe.
There are two files "cifar10_coefficients_chw_big.c" and "cifar10_coefficients_chw_small.c" that list all the coefficients of the convolution layers.
I wonder how to transform the pre-trained model into that coefficient files.
Is there any automation tool or flow could support the transformation?

--------------------------------------------------------------------------------
## Development Environment
- **HOST OS**
    Win10 64 bit

- **TOOLCHAIN**
    gnu toolchain

- **BOARD**
    ARC IoTDK

- **ARC CORE**
    arcem9d

--------------------------------------------------------------------------------
# Question
   I wonder how to transform the pre-trained model into that coefficient files.
   Is there any automation tool or flow could support the transformation?

**Comment by vonhust** [comment]
pls move this issue to embarc mli repo: https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_mli
