### ISSUE TITLE
the led of max30102 device can not be lightened

### ISSUE THREAD

**Issue by ym0v0my** [foss-for-synopsys-dwc-arc-processors/embarc_osp#115]
# Issue Summary
- **Type**: *Question*
- **Category**: *Example* | *Usability* | *Bug*
- **Priority**:  *High*
- **Release Version**:  2016.1.12 v2.2

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**

   Windows 7, 32Bit 

- **TOOLCHAIN**
ARC GNU 2016.03.

- **BOARD**
    Input the board name and its version.
    For example, EMSK 2.2 

- **ARC CORE**
ARC EM7D.

## Bug Description
We brought a max30102 module to support the project recently.But the ir led and red led of the module can not be lightened when we connect the four pins(VCC GND SDA SCL) to the board. 
We found out some videos about max30102 ,they showed that it works well with some boards,such as STM32 and Ardunio,by connecting the four pins we have mentioned above.

**Comment by YuguoWH** [comment]
Please make sure your connection is correct, as well as the module and your code. 
Also, please make sure pin_mux is correctly set.
