### ISSUE TITLE
A question about C++ support

### ISSUE THREAD

**Issue by XiangcaiHuang** [foss-for-synopsys-dwc-arc-processors/embarc_osp#12]
# Issue Summary
- **Type**: *Question*
- **Category**: *Example*
- **Priority**:*Low*
- **Release Version**: 2017.03

## Development Environment
- **HOST OS**
    Windows 7, 64Bit

- **TOOLCHAIN**
    ARC GNU 2017.03

- **BOARD**
    EMSK 2.2

- **ARC CORE**
    EM7D

# Question
   I notice that there is an example named embARC C++ support Test. I want to know Whether embARC  supports all C ++ syntax or not? So it has supported C/C++ now? But I couldn't find any information about it in the embARC introduction.

**Comment by fanghuaqi** [comment]
For C++ support, this depended on the compiler a lot, you can refer to compiler manual to see what it support, and not all the C++ features can be supported in embARC.
