### ISSUE TITLE
Hang while running with specific TCF 

### ISSUE THREAD

**Issue by benhaim1** [foss-for-synopsys-dwc-arc-processors/embarc_osp#123]
# Issue Summary
- **Type**: *Bug*
 *Tools*
- **Priority**:*High* 
- **Release Version**:  MW 2019.03 

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**
 FreeRTOS

- **TOOLCHAIN**
MW 2019.03 

- **BOARD**
nSIM

- **ARC CORE**
    Input the ARC core name, such as EM6.

## Bug Description
 When using specific TCF file the run is stuck as follows:

C:\Users\benhaim\Downloads\embarc_osp-master\example\freertos\kernel>gmake BOARD=nsim -j4 run TCF=arc_em6_mini_enhanced.tcf

freeRTOS: there are 4 task priorities.
Error in evaluating expression `&xQueueRegistry'.
Current task is 0: denotes current task in _arc_reset.
-----------------------------------------------------------
 ____                                _ ____
|  _ \ _____      _____ _ __ ___  __| | __ ) _   _
| |_) / _ \ \ /\ / / _ \ '__/ _ \/ _` |  _ \| | | |
|  __/ (_) \ V  V /  __/ | |  __/ (_| | |_) | |_| |
|_|   \___/ \_/\_/ \___|_|  \___|\__,_|____/ \__, |
                                             |___/
                     _       _    ____   ____
       ___ _ __ ___ | |__   / \  |  _ \ / ___|
      / _ \ '_ ` _ \| '_ \ / _ \ | |_) | |
     |  __/ | | | | | |_) / ___ \|  _ <| |___
      \___|_| |_| |_|_.__/_/   \_\_| \_\\____|
------------------------------------------------------------

embARC Build Time: Jun 18 2019, 20:05:00
Compiler Version: Metaware, 4.2.1 Compatible Clang 6.0.1 (branches/release_60)
Benchmark CPU Frequency: 200000000 Hz
Benchmark will run 200 times, please wait about 400 ms
perf timer init failed

**Comment by IRISZZW** [comment]
In embarc_osp project we get some hardware configuration from tcf file.

We generate CPU Frequency from macro definition core_config_clock_speed defined in tcf file, CPU Frequency = core_config_clock_speed*1000000. So check the core_config_clock_speed defined in your tcf file.

In freertos kernel example, we use TIMER1 for perf timer, so you need add TIMER1 support in tcf file.
