### ISSUE TITLE
SECURESHIELD_SECURE_CALL does not preserve FP

### ISSUE THREAD

**Issue by jsun85** [foss-for-synopsys-dwc-arc-processors/embarc_osp#14]
# Issue Summary
- **Type**: *Bug*
- **Category**: *Library*
- **Priority**: *High*
- **Release Version**: 2017.03

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**
    Ubuntu 16.04 LTS, 64Bit

- **TOOLCHAIN**
    ARC GNU 2017.03.

- **BOARD**
    EMSK 2.3

- **ARC CORE**
    EM7D.

## Bug Description
   SECURESHIELD_SECURE_CALL is used to generate call to sjli_secureshield_int_ops for a group of functions defined in library/secureshield/export/src/interrupts.c. The problem is sjli_secureshield_int_ops and sjli_secureshield_sys_ops does not preserver FP register, in stage CLEAR_SCRATCH_REGS it set FP to 0. This is not a critical problem when build with O2, there FP register is not used, but when build with OLEVEL=O0, FP is used to save SP, and restore SP from FP cause SP be set to 0. This can be easily validated by build test_case project with OLEVEL=O0, you will see a exception in the beginning of main function at:

        EMBARC_PRINTF("timer0 interrupt prioirty is:%d\r\n", secureshield_int_pri_get(INTNO_TIMER0));

--------------------------------------------------------------------------------
# Enhancement
   Save FP to stack in SECURESHIELD_SECURE_CALL.

--------------------------------------------------------------------------------
# Question

**Comment by vonhust** [comment]
This issue is fixed in the commit 963fd44929f2a72f33d5c24848221a11773600ac. @jsun85 please pull the latest code and try.
