### ISSUE TITLE
make parameter LINKER_SCRIPT_FILE is not documented

### ISSUE THREAD

**Issue by achuykov** [foss-for-synopsys-dwc-arc-processors/embarc_osp#144]
# Issue Summary
- **Type**:  *Enhancement* 
- **Category**:  *Documentation*
- **Priority**: *Medium* 
- **Release Version**: 2019.06

--------------------------------------------------------------------------------

# Enhancement
   Customer wants to use customized linker script without template patching. It is possible to use LINKER_SCRIPT_FILE parameter for make/gmake but is not documented. Please update documentation. 
Usage example:
`gmake LINKER_SCRIPT_FILE=MY.ld `

**Comment by YuguoWH** [comment]
An update commit c361bc1 has been pushed to fix this issue. Thanks for your advice!
