### ISSUE TITLE
ad7991

### ISSUE THREAD

**Issue by darko262** [foss-for-synopsys-dwc-arc-processors/embarc_osp#161]
When I call the ad7991_adc_read function
How often does the ad7991 A / D converter work?

**Comment by YuguoWH** [comment]
Hi @darko262 . The AD7991 normally remain in a shutdown state, powering up only for conversions. The conversion process is controlled by a command mode, during which each I2C read operation initiates a conversion and returns the result over the I2C bus.
When ad7991_adc_read () is called, the driver initiates one read and reads data from previously selected channels. Therefore it only wake-up AD7991 once.
If you are interested in the ADC power mode, please check AD7991 datasheet for detail power data.

**Comment by darko262** [comment]
Thank you
