### ISSUE TITLE
Missing makefile arguments for building, running and debugging

### ISSUE THREAD

**Issue by achuykov** [foss-for-synopsys-dwc-arc-processors/embarc_osp#170]
# Issue Summary
- **Type**: *Bug* 
- **Category**: *Documentation* 
- **Priority**:  *Medium* 
- **Release Version**: trunk

--------------------------------------------------------------------------------
# Bug

- **BOARD**
    EMSK 2.3 

## Bug Description
   A copy-paste issue in code snippets in EMSK docs (see links). So, make arguments are same for building, running and debugging
   
1. https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_osp/blob/master/doc/documents/board/emsk.rst#building
2. https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_osp/blob/master/doc/documents/board/emsk.rst#running
3. https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_osp/blob/master/doc/documents/board/emsk.rst#debugging

**Comment by YuguoWH** [comment]
fixed via ed742d6
