### ISSUE TITLE
Lib secureshield bad initialisation of containers .bss and .data sections

### ISSUE THREAD

**Issue by Jeff006** [foss-for-synopsys-dwc-arc-processors/embarc_osp#22]
# Issue Summary
- **Type**: *Bug*
- **Category**: *Library*
- **Priority**: *High*
- **Release Version**: Specified version such as 2017.03

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **Windows 7, 64Bit**

- **Compiler Version: ARC GNU, 7.1.1 20170710**

- **User specific**

- **EM6**

## Bug Description
In library secureshield, initialisation of containers .bss and .data sections seems not to be done. In file secureshield_vmpu_arc.c (both v1 and v2), in function vmpu_ac_container the two lines:

memcpy(container_cfg->data_start, container_cfg->data_load_start, VMPU_REGION_SIZE(container_cfg->data_end, container_cfg->data_start));
memset(container_cfg->bss_start, 0, VMPU_REGION_SIZE(container_cfg->bss_end, container_cfg->bss_start));

seem to do nothing because data_end/bss_end is always greater or equal to data_start/bss_start respectively. It seems end/start have been swapped in macro VMPU_REGION_SIZE parameters (typo ?)

--------------------------------------------------------------------------------
# Enhancement
Replace the two mentioned lines by:

memcpy(container_cfg->data_start, container_cfg->data_load_start, VMPU_REGION_SIZE(container_cfg->data_start, container_cfg->data_end));
memset(container_cfg->bss_start, 0, VMPU_REGION_SIZE(container_cfg->bss_start, container_cfg->bss_end));

Example is working with this correction.

**Comment by vonhust** [comment]
This bug is already fixed. Pls pull the latest code.
