### ISSUE TITLE
IoT DK UART1 and UART2 cannot be used in interrupt mode

### ISSUE THREAD

**Issue by YuguoWH** [foss-for-synopsys-dwc-arc-processors/embarc_osp#24]
# Issue Summary
- **Type**: *Bug*
- **Category**: *Device HAL*
- **Priority**: *Medium*
- **Version**:  94ee519  at branch feature/iotdevkit

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**
   Windows 10, 64Bit

- **TOOLCHAIN**
 MWDT build (2017.09/rel)

- **BOARD**
    IOTDK

- **ARC CORE**
    arcem9d

## Bug Description
   The TX of UART1 and UART2 are fine but will hang trying to receive any message with interrupt. Seems like signals are unable to be received in UART1&2.

**Comment by qiangg** [comment]
The driver is out-of-date and will be updated soon.

**Comment by vonhust** [comment]
already fixed
