### ISSUE TITLE
No I2C polling mode in the IoT DK

### ISSUE THREAD

**Issue by YuguoWH** [foss-for-synopsys-dwc-arc-processors/embarc_osp#25]
# Issue Summary
- **Type**: *Enhancement*
- **Category**:  *Device HAL*
- **Priority**:  *Medium*
- **Version**:  94ee519 at branch feature/iotdevkit

--------------------------------------------------------------------------------
## Development Environment
- **HOST OS**
   Windows 10, 64Bit

- **TOOLCHAIN**
 MWDT build (2017.09/rel)

- **BOARD**
    IOTDK

- **ARC CORE**
    arcem9d

## Enhancement
   The interrupt mode of DFSS I2C driver is supported in current version, but there's no I2C polling mode.

**Comment by qiangg** [comment]
The DFSS I2C polling mode will be updated soon.

**Comment by vonhust** [comment]
already added
