### ISSUE TITLE
HSDK onboard WiFi support

### ISSUE THREAD

**Issue by YuguoWH** [foss-for-synopsys-dwc-arc-processors/embarc_osp#26]
# Issue Summary
- **Type**: *Question*
- **Category**: *Device HAL*
- **Priority**: *Medium*

--------------------------------------------------------------------------------
# Question
   Is there any method to use the onboard WiFi module on HSDK? I wonder if there will be any driver provided, THX.

**Comment by qiangg** [comment]
Pmod WiFi is supported in the current version. For the HSDK, the driver of onboard WiFi is in development.

**Comment by vonhust** [comment]
Because of the firmware,  the onboard WiFi only can work with linux. no plan to add it in embarc,
