### ISSUE TITLE
Some network and ntshell examples are not available for IoT DK

### ISSUE THREAD

**Issue by YuguoWH** [foss-for-synopsys-dwc-arc-processors/embarc_osp#27]
# Issue Summary
- **Type**: *Bug*
- **Category**: *Example*
- **Priority**: *Medium*
- **Version**:  94ee519 at branch feature/iotdevkit

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**
   Windows 10, 64Bit

- **TOOLCHAIN**
 MWDT build (2017.09/rel)

- **BOARD**
    IOTDK

- **ARC CORE**
    arcem9d

## Bug Description
  I've tried examples provided in example folder, however some network example requires ntshell whereas ntshell example is not support for IOTDK yet.

**Comment by qiangg** [comment]
The reason is the memory limitation of IoT DK. Need to optimize the network and shell examples to reduce the size of them.

**Comment by vonhust** [comment]
already fixed
