### ISSUE TITLE
file folder ide_projects missing in your code packet

### ISSUE THREAD

**Issue by ZuoJiawei** [foss-for-synopsys-dwc-arc-processors/embarc_osp#3]
# Issue Summary
- **Type**: *Question*
- **Category**:  *Example* | *Documentation*
- **Priority**: *Medium* 
- **Release Version**: 2017.03
--------------------------------------------------------------------------------
# Question
   After reading [embARC Documentation](http://embarc.org/embarc_osp/doc/embARC_Document/html/index.html#sect_intro_overview)
I find an file folder being taged as **ide_projects** listed in the document overview is missing in your latest code release. Did you change this folder's name (if so what is folder's name)or just delete it?

**Comment by fanghuaqi** [comment]
Hi Jiawei,

For *ide_projects* folder, it only existed in release package of embARC OSP, you can get the release package [here](https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_osp/releases). If you just clone the repo source code, you can only try in command line mode. Or you can copy the *ide_projects* folder in release package, and pasted in your source code root of embARC OSP.

Thanks
Huaqi

**Comment by fanghuaqi** [comment]
Maybe we can take this explanation as FAQs.
