### ISSUE TITLE
Question about gpio interrupt priority

### ISSUE THREAD

**Issue by ltmono** [foss-for-synopsys-dwc-arc-processors/embarc_osp#35]
# Issue Summary
- **Type**:  Question
- **Category**: Device HAL | Example
- **Priority**: Medium
- **Release Version**:  2017.12

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**
    Windows10 , 64Bit

- **TOOLCHAIN**
    ARC GNU 2017.09.
   
- **BOARD**
    EMSK 2.2

- **ARC CORE**
    EM7D.

## Bug Description

--------------------------------------------------------------------------------
# Enhancement

--------------------------------------------------------------------------------
# Question
Hello！I want to use a few GPIO devices,and I want to set different interrupt priority for  them.However,I can only find this fuction:

arc_int_pri_set(INTNO_GPIO, INT_PRI_MAX)

It seems that all the GPIO devices can only be set as same priority.So,I want to ask if there is any oher way to set interrupt priority.Thanks!

**Comment by fanghuaqi** [comment]
The GPIO Pin don't have a interrupt priority, if you look at the source code https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_osp/blob/master/device/ip/designware/gpio/dw_gpio.c#L498, you will find the GPIO pin interrupt will be handled from 0 to 31, so GPIO bit 0 interrupt will be handled first, GPIO bit 31 will be handled the last, if interrupt happened at the same time.

Thanks
Huaqi
