### ISSUE TITLE
spelling mistake in embARC guide documentation.

### ISSUE THREAD

**Issue by IRISZZW** [foss-for-synopsys-dwc-arc-processors/embarc_osp#36]
# Issue Summary
- **Type**: *Bug* 
- **Category**:  *Documentation* 
- **Priority**:  *Low*
- **Release Version**: 2017.12

--------------------------------------------------------------------------------
# Bug

## Bug Description
   there is a spelling mistake in embARC guide documentation.
   location is embarc_osp/doc/documents/middleware/middleware.rst.
   line 3 in middleware.rst spelled "Middlwares".
   this spelling mistake could be seen signally  as it is a title of this 
   webpage(http://embarc.org/embarc_osp/doc/build/html/middleware/middleware.html).
![qq 20180704153637](https://user-images.githubusercontent.com/16890595/42316636-eb4f6424-807c-11e8-94b9-c184e8cb9cba.png)

**Comment by BabaYB** [comment]
I got  two more spelling mistakes in the doucument.
- ARC processors/Board level start up/OS/`Create WIFI if` seems there is a unnecessary dot
- Libraries/secureshield/6.Compiling&debug/`linker_xx.ldf: the generated linker script for normal applicatio` word `applicatio` missed a `n`

**Comment by BabaYB** [comment]
And many HTML labels are used but not works.
For example, in /example/barematel/simple_bootloader, label `<em>` & `<b>` as following
---
![image](https://user-images.githubusercontent.com/16234146/42439335-36c50a74-8395-11e8-8286-f83ea2ff49ee.png)
![image](https://user-images.githubusercontent.com/16234146/42439386-5e931c44-8395-11e8-9749-6b037946db34.png)

**Comment by YuguoWH** [comment]
Hi @IRISZZW, could you please _fork_ the repo and then use _Pull Request_ to help submit your fixes, thank you very much.

**Comment by fanghuaqi** [comment]
@IRISZZW I have merged the pull request #38  that fixed 1 issue, please create a new pull request to fix other issues submit by others.

**Comment by fanghuaqi** [comment]
Fixed in pull request #41
