### ISSUE TITLE
Many pictures can't show in /example document

### ISSUE THREAD

**Issue by BabaYB** [foss-for-synopsys-dwc-arc-processors/embarc_osp#37]
# Issue Summary
- **Type**: *Documentation*
- **Release Version**: Specified version such as 2016.05 or All

--------------------------------------------------------------------------------
   When I read the document of /example/baremetal/simple_bootloader, I found many pictures can't show but image links.

**Comment by YuguoWH** [comment]
Hi @BabaYB , would you please use _pull request_ to help submit your fix, thanks.

**Comment by fanghuaqi** [comment]
See pull request #41

**Comment by fanghuaqi** [comment]
Fixed by pull request #41
