### ISSUE TITLE
Bug in udma example,BD_VER=11

### ISSUE THREAD

**Issue by ZuoJiawei** [foss-for-synopsys-dwc-arc-processors/embarc_osp#4]
# Issue Summary
- **Type**: *Bug*
- **Category**: *Example*
- **Priority**: *Medium* 
- **Release Version**: 2017.03

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**
    Windows 10, 64Bit

- **TOOLCHAIN**
    ARC GNU 2017.03.

- **BOARD**
    EMSK 1.1 

- **ARC CORE**
    EM6.

## Bug Description
   When I run the udma example(located at example->baremetal->udma),my putty console shows me the bug message (part of the message are listed below):
   default cpu exception handler
   exc_no:2, last sp:0x10008834, ecr:0x00020000, eret:0x10002b24
I try to change the ram into external ram by rewriting MARCRO  
#define REGION_ROM	EXT_RAM//ICCM
#define REGION_RAM	EXT_RAM//DCCM
in **appl_mem_config.h** ,but the problem still exits.

**Comment by fanghuaqi** [comment]
uDMA only existed in EMSK 2.2 and EMSK 2.3, you can refer to EMSK user manual.
