### ISSUE TITLE
Bug in arc_cxx_startup.c

### ISSUE THREAD

**Issue by jsun85** [foss-for-synopsys-dwc-arc-processors/embarc_osp#5]
# Issue Summary
- **Type**: *Bug*
- **Category**: *Library*
- **Priority**: *High*
- **Release Version**: 2017.03

--------------------------------------------------------------------------------
# Bug
Wrong initial value of variable i in function __do_global_dtors_aux

## Development Environment
Ubuntu 16.04 LTS, 64 bit

- **TOOLCHAIN**
ARC GNU 2016.09

- **BOARD**
EMSK 2.3

- **ARC CORE**
EM7D

## Bug Description
Line 115 in function __do_global_dtors_aux initialize variable i to wrong value 0, i should start from 1 but not 0, 0 cause processor jump to a random address (in most case address 0) and execute from there, that cause application terminate in a wrong status.

In arc_cxx_startup.c
`109 void __do_global_dtors_aux(void)`
`110 {`
`111         unsigned int nDtors;`
`112         unsigned int i;`
`113 `
`114         nDtors = (unsigned int)__DTOR_LIST__[0];`
`115         i = 0;`
`116 `
`117         while (i <= nDtors) {`
`118                 __DTOR_LIST__[i++]();`
`119         }`
`120 }`
i = 0 should be i = 1

--------------------------------------------------------------------------------
# Enhancement
Initialize variable i to 1.

--------------------------------------------------------------------------------
# Question

**Comment by vonhust** [comment]
It's bug. Fixed and committed.  Thanks for report. Now close it.
