### ISSUE TITLE
Doc improvement suggestion on udma example

### ISSUE THREAD

**Issue by ZuoJiawei** [foss-for-synopsys-dwc-arc-processors/embarc_osp#7]
# Issue Summary
- *Enhancement*
- **Category**: *Example*
- **Priority**:*Low*
- **Release Version**: 2017.03
--------------------------------------------------------------------------------
# Enhancement
When you go to **/example/baremetal/arc_feature/udma/main.c**,you can find the section "extra comment".In this section,I think supported board version should be noted since it's important for users to tell which device this example can run on.
For instance:
### Extra Comments
Please notify that this device supports: boards ver 2.2 or above.

**Comment by fanghuaqi** [comment]
We can add notice about this in the doc later.

**Comment by fanghuaqi** [comment]
Fixed
