### ISSUE TITLE
How to start ARC image from DDR beyond 0x0

### ISSUE THREAD

**Issue by asampadeh** [foss-for-synopsys-dwc-arc-processors/embarc_osp#71]
# Issue Summary
- **Type**:  *Question*
- **Category**: *Build System* 
- **Priority**: *Urgent*
- **Release Version**: metaware_vM-2016.12

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**
    Input the host os name and its version.
    For example, Windows 7, 64Bit | Debian Linux 8.6, 64Bit

- **TOOLCHAIN**
metaware_vM-2016.12

- **BOARD**
nSIM

- **ARC CORE**
EM7D.

## Bug Description

--------------------------------------------------------------------------------
# Enhancement

--------------------------------------------------------------------------------
# Question
I tried simply by changing the LCF file to show DDR region from 0x00010000 instead starting from 0, but only the main.dis and main.hex starting address changed to 00001000 but main.bin (which is going to real DDR chip) still holding the address of 0.
Anybody can help with the compile/linker option to achieave this?

Thanks for advise

**Comment by vonhust** [comment]
Do you use embARC_osp ? As I know, embarc_osp will not generate main.dis, also no LCF file.

**Comment by asampadeh** [comment]
Hi @vonhust , no, I am using metaware debugger environment

**Comment by vonhust** [comment]
@asampadeh  it's a little difficult to reproduce your issuse as we are the maintainer of embarc osp.

**Comment by vonhust** [comment]
not an embarc_osp related issue
