### ISSUE TITLE
MetaWare debugger FreeRTOS awareness

### ISSUE THREAD

**Issue by mnasr93** [foss-for-synopsys-dwc-arc-processors/embarc_osp#77]
# Issue Summary
- **Type**: *Question*
- **Category**:  *OS* | *Tools* 
- **Release Version**: Specified version such as 2016.05 or All

-----------------------------------------------------------------------------
# Question
I have an issue when i enable FreeRTOS awareness in metaware debugger.
it was working fine and all tasks is displayed in debug window, each of them with its function call stack.
now after push and pop 1 more register after r25 in SAVE_CALLEE_REGS and RESTORE_CALLEE_REGS respectively (i.e SAVE_R58_R59, RESTORE_R58_R59) which found in file "arc_asm_common.h" the debugger only shows function call stack of the current running task only, and the other tasks show (symbols not available).

Thanks.

**Comment by iguryanov** [comment]
Hi, 

could you please share your embarc_osp release version, ARC GNU tools version and MWDT release name? (I am pretty sure 2016.05 is a typo for MWDT). Make string (or your default values) for your mebarc_osp would also help as it comes with platform configuration options. 

Regards,
Igor.

**Comment by MuhammadMostafa** [comment]
Hi Igor,

embarc_osp release version: at master branch
Commit No : 4a54cf45ab1f11fc48a78416bfafbde414024892

ARC GNU tools version: Release (4.7.1a)  -My issue related to MW debugger-

MWDT:
Version: 10.7
Build id: 20170622

You can try to debug while using the latest version of embarc-osp at which they push more registers than older versions in the macro SAVE_CALLEE_REGS

#if ARC_FEATURE_FPU_DSP_CONTEXT
	SAVE_R58_R59
	SAVE_FPU_REGS
	SAVE_DSP_REGS
#endif

**Comment by iguryanov** [comment]
ok, thank you. I'll update soon as I setup local testbench for this. 

Regards,
Igor.
