### ISSUE TITLE
Bug in /board/hsdk/hsdk.mk

### ISSUE THREAD

**Issue by BarryWang2017** [foss-for-synopsys-dwc-arc-processors/embarc_osp#82]
# Issue Summary
- **Type**: *Bug* 
- **Category**:  *Example* 
- **Priority**: *High* 
- **Release Version**: 2018.12

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**
    Ubuntu 18.04.2 LTS  64Bit

- **TOOLCHAIN**    
    ARC GNU 2018.09.

- **BOARD**
    HSDK

- **ARC CORE**
    archs38

## Bug Description
   There is a bug on line 63 of the `<embarc_osp>/board/hsdk/hsdk.mk`. 
```
OPENOCD_CFG_FILE = $(OPENOCD_SCRIPT_ROOT)/board/snps_axs103_hs38.cfg
```

--------------------------------------------------------------------------------
# Enhancement
   `snps_axs103_hs38.cfg` should be replaced with `snps_hsdk.cfg`.
```
OPENOCD_CFG_FILE = $(OPENOCD_SCRIPT_ROOT)/board/snps_hsdk.cfg
```

**Comment by vonhust** [comment]
fixed
