### ISSUE TITLE
A bug in /board/emsk/emsk.h

### ISSUE THREAD

**Issue by ZuoJiawei** [foss-for-synopsys-dwc-arc-processors/embarc_osp#9]
# Issue Summary
- **Type**: *Bug*
- **Category**: *Device HAL*
- **Priority**: *High*
- **Release Version**: 2017.03

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**
    Windows 10, 64Bit 

- **TOOLCHAIN**
    ARC GNU 2017.03.

- **BOARD**
    EMSK 1.1

- **ARC CORE**
    EM6.

## Bug Description
   Before :
   #define PMWIFI_MRF24G			0
   #define PMWIFI_RW009			1 
   After,Should be changed into :
   #define PMWIFI_MRF24G			1
   #define PMWIFI_RW009			0
   Since  Digilent PMOD WIFI(MRF24WG0MA) is used as Extra Required Peripherals in 
   **/example/freertos/net/httpserver** and **/example/freertos/net/ntshell**

**Comment by fanghuaqi** [comment]
Hi Jaiwei,

      The `PMWIFI_MRF24G` and `PMWIFI_RW009` in `/board/emsk/emsk.h` is not enabling or disabling this modules, but the ID like thing, treat `PMWIFI_MRF24G` as ID 0 WiFi, which is used in pmwifi.h, 
```
/** BOARD_WIFI_SEL can be changed in board.mk by changing WIFI_SEL, possible choices defined in emsk.h */
#ifndef BOARD_WIFI_SEL
#define BOARD_WIFI_SEL			PMWIFI_MRF24G
#endif
```

Thanks
Huaqi
